[build]
  command = "npm run deployment"
  publish = "deploy"

[[redirects]]
  from = "/demo"
  to = "/#/collections/pages/entries/demo"
  status = 301

[[redirects]]
  from = "/docs"
  to = "https://github.com/adamjkb/netlify-cms-widget-select-async#readme"
  status = 301
